# Generated by Django 4.1.5 on 2023-01-23 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('member', 'Базовый пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='member', max_length=15)),
                ('age', models.PositiveSmallIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.location')),
            ],
        ),
    ]
