# Generated by Django 4.1.5 on 2023-01-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_remove_advertisement_address_advertisement_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Местоположение', 'verbose_name_plural': 'Местоположения'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='advertisement',
            order_with_respect_to='name',
        ),
        migrations.AlterOrderWithRespectTo(
            name='category',
            order_with_respect_to='name',
        ),
        migrations.AlterOrderWithRespectTo(
            name='location',
            order_with_respect_to='name',
        ),
        migrations.AlterOrderWithRespectTo(
            name='user',
            order_with_respect_to='username',
        ),
    ]
