# Generated by Django 4.1.5 on 2023-01-27 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_advertisement_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='location',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='user',
            order_with_respect_to=None,
        ),
    ]
